### ISSUE TITLE
Design: ordered ignore-missing carry-forward (LOCF)

### ISSUE THREAD

**Issue by elong0527** [elong0527/yamaa#91]
## Next step

Implement one narrow window expression for the immediate use case:

- return the most recent strictly preceding non-missing value within declared
  groups and order;
- define start-of-sequence, ties, missing group/order values, and type errors;
- add one positive carry-forward example and focused negative/edge examples; and
- update R007 plus `schema_expression_window.yaml`.

Do not combine this with interval matching, grouped aggregates, or row
construction; the explicit planning spine remains responsible for adding rows.

Part of #49. Split from #50 because ordered ignore-missing propagation is a column/window capability distinct from T5 interval matching and multi-grain aggregate composition.

## Problem

A specification cannot obtain the most recent preceding non-missing value within declared groups and order. `row_value` reads one fixed nonzero offset and cannot skip an unknown run of missing values. `baseline_value` broadcasts one flagged record to an entire partition rather than selecting a changing predecessor. Recursive self-reference is a dependency cycle.

This is concretely required by `pharmaverse/admiral` commit `e32e5689d7fd03e224ddbcfc369c332c5df837d9`, `R/derive_locf_records.R` (especially lines 241-339): after expected observations are added, records are ordered and the latest non-missing analysis value is carried through an unknown number of later missing rows.

The explicit planning spine introduced in PR #76 can create expected rows, but it does not fill an ordered sequence with the changing latest predecessor.

## Required capability

Define a portable ordered ignore-missing expression (whether named `locf` or otherwise) that:

- partitions by declared `group_by` columns;
- orders by declared `order_by` terms;
- returns the most recent strictly preceding non-missing source value;
- remains distinct from `baseline_value`'s one-record broadcast; and
- composes with expected-row construction without recursive self-reference or unstated execution order.

## Acceptance criteria

- [ ] Start-of-sequence missing values have deterministic behavior.
- [ ] Runs of one and multiple missing values are covered.
- [ ] Ordering ties have deterministic normative behavior or fail closed.
- [ ] Missing group/order inputs and incompatible types have specified behavior.
- [ ] Schema and normative rules include positive and negative/edge examples.
- [ ] Expected-row addition followed by carry-forward composes without a dependency cycle.
- [ ] R and Python implementations reproduce identical filled sequences.
- [ ] Documentation distinguishes ordered ignore-missing propagation from `row_value`, `baseline_value`, aggregates, and cross-dataset record lookup.

## Development note

A retained exploratory branch exists at `schema-gap/issue-50-ordered-locf`. It was created from historical `main` commit `99f322e9a81544a44ddb7ecf49d46f2135abb168` and must be rebased before implementation work resumes.

## References

- `yaml/schema_expression_window.yaml`
- `yaml/examples/adam-advs-once-measured-carry-forward/`
- `yaml/examples/negative-row-value-self-reference/`
- PR #76
- closed issue #32
- #50
